import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LoaderWrapper from './components/LoaderWrapper'
import { BackgroundEffects } from "./components/BackgroundEffects";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className="relative h-full">
        <BackgroundEffects/>  
        <LoaderWrapper>
          {children}
        </LoaderWrapper>
        
      </body>
    </html>
  )
}
