import type { Metadata } from "next";
import LoaderWrapper from './components/LoaderWrapper'
import { BackgroundEffects } from "./components/BackgroundEffects";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className="relative h-full">
        <BackgroundEffects/>  
        <LoaderWrapper>
          {children}
        </LoaderWrapper>
        
      </body>
    </html>
  )
}
